### ISSUE TITLE
Add ability to get closest result from response array

### ISSUE THREAD

**Issue by curranjm** [codeforboston/BrooklineVoiceApp#36]
If we get multiple results from the arcgis server, we currently just return the first one.

Add functionality to figure out what the closest location is.

**Comment by thiteixeira** [comment]
@curranjm we did something similar for the food truck intent in the Boston app, where we passed parameters to the ArcGIS server that replies with the list of features that falls within a certain range. I believe that with a few tweaks you can get the closest one.

**Comment by jmartini** [comment]
Closing. This was done in PR #41
