### ISSUE TITLE
Implement StopIntent

### ISSUE THREAD

**Issue by jmartini** [codeforboston/BrooklineVoiceApp#45]
When a user tells our skill to exit, we need to provide an exit message and handle the "AMAZON.StopIntent" that is sent to our skill.

See [Canceling and stopping documentation](https://developer.amazon.com/en-US/docs/alexa/custom-skills/standard-built-in-intents.html#about-canceling-and-stopping).

**Comment by EndyPremier** [comment]
I am curious if "AMAZON.CancelIntent" could cause the same exit message as intended with "AMAZON.StopIntent"?

**Comment by jmartini** [comment]
Closed with #46
